feat: add typosquatting analyzer for go modules
DataDog/guarddog pull request #481
Opened 2024-10-30 13:53 UTC by bthuilot

## Changes
- Adds `typosquatting` analyzer for go modules
- Adds `top_go_packages.json` which contains top ~3000 go modules
  - List was gathered by searching for go.mod files on GitHub with more than 50 stars
  - Parsed the go.mod files and counted the amount of each pacakge used, then took all packages used in more than 10 repos

2024-10-30 14:06 UTC, sobregosodd commented
> which contains top 500 go modules

@bthuilot mind that we are using about 80k packages in other ecosystems for this detection

2024-11-04 12:14 UTC, juliendoutre reviewed
Looks good to me but noticed a few commented code sections which may not be intentional?

2024-11-04 12:14 UTC, juliendoutre commented on guarddog/analyzer/metadata/go/typosquatting.py
> +        # )
nit: dead code?

2024-11-04 12:14 UTC, juliendoutre commented on guarddog/analyzer/metadata/go/typosquatting.py
> +        #         json.dump(top_packages_information, f, ensure_ascii=False, indent=4)
dead code?

2024-11-04 12:14 UTC, juliendoutre commented on guarddog/analyzer/metadata/go/typosquatting.py
> +            # if datetime.now() - update_time <= timedelta(days=30):
dead code?

2024-11-12 16:02 UTC, sobregosodd requested changes

2024-11-13 13:30 UTC, sobregosodd approved these changes

2024-11-13 19:15 UTC, merged